language: node_js

node_js:
  - 10

services:
  - postgres

env:
  global:
    NODE_ENV=development
  
before_script:
  - yarn db:setup

jobs:
  include:
    - stage: test
      script: npm test

notifications:
  email:
    on_success: never
    on_failure: change
